=== meemo00/cherieweb/signup.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">


<xs:element name="users"> 
	  <xs:complexType>
	  <xs:sequence>
	  <xs:element name="user" type="userdetails" minOccurs="1" maxOccurs="unbounded"/>   
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:complexType name="userdetails">
<xs:sequence>
    <xs:element name="firstname" type="xs:string" minOccurs="0"/>
    <xs:element name="lastname" type="xs:string" minOccurs="0"/>
	
	<xs:element name="username" minOccurs="1">
	 <xs:simpleType>
	    <xs:restriction base="xs:string">   
	      <xs:minLength value="8"/>
	      <xs:maxLength value="16"/>
	    </xs:restriction>
	 </xs:simpleType>
	</xs:element>
	
    <xs:element name="password" minOccurs="1">
	  <xs:simpleType>
	    <xs:restriction base="xs:string">
	      <xs:minLength value="8"/>
	      <xs:maxLength value="16"/>
          <xs:pattern value="(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+"/>
	    </xs:restriction>
	  </xs:simpleType>
	</xs:element>
	
	<xs:element name="fulladdress" minOccurs="1">
	  <xs:simpleType>
	    <xs:restriction base="xs:string">
	      <xs:minLength value="10"/>
	      <xs:maxLength value="50"/>
	    </xs:restriction>
	  </xs:simpleType>
	</xs:element>
	
    <xs:element name="postcode" minOccurs="1">
	  <xs:simpleType>
	    <xs:restriction base="xs:integer">
	      <xs:totalDigits value="5"/>
	    </xs:restriction>
	  </xs:simpleType>
	</xs:element>
	
	<xs:element name="city" minOccurs="1">
	  <xs:simpleType>
	   <xs:restriction base="xs:string">
	     <xs:minLength value="2"/>
	     <xs:maxLength value="20"/>
	   </xs:restriction>
	  </xs:simpleType>
	</xs:element>	
	
	<xs:element name="state" minOccurs="1">
	  <xs:simpleType>
	    <xs:restriction base="xs:string">
	      <xs:enumeration value="Perlis"/>
	      <xs:enumeration value="Kedah"/>
	      <xs:enumeration value="Pulau Pinang"/>
	      <xs:enumeration value="Perak"/>
	      <xs:enumeration value="Selangor"/>
	      <xs:enumeration value="Negeri Sembilan"/>
	      <xs:enumeration value="Melaka"/>
	      <xs:enumeration value="Johor"/>
	      <xs:enumeration value="Pahang"/>
	      <xs:enumeration value="Terengganu"/>
	      <xs:enumeration value="Kelantan"/>
	      <xs:enumeration value="Sabah"/>
	      <xs:enumeration value="Sarawak"/>
	      <xs:enumeration value="Wilayah Persekutuan Kuala Lumpur"/>
	      <xs:enumeration value="Wilayah Persekutuan Putrajaya"/>
	      <xs:enumeration value="Wilayah Persekutuan Labuan"/>
	    </xs:restriction>
	  </xs:simpleType>
	</xs:element>
	
	<xs:element name="phone" minOccurs="1">
	  <xs:simpleType>
	     <xs:restriction base="xs:string">
	       <xs:pattern value="\d{3}[-]\d{7}"/>
	       <xs:length value="11"/>
	     </xs:restriction>
	  </xs:simpleType>
	</xs:element>
	
	<xs:element name="email" minOccurs="1">
	  <xs:simpleType>
	     <xs:restriction base="xs:string">
	      <xs:pattern value="[^@\s]+@[^@\s]+\.[^@\s]+"/>
	     </xs:restriction>
	  </xs:simpleType>
	</xs:element>
	
</xs:sequence>
</xs:complexType>
</xs:schema>

=== meemo00/cherieweb/signup.xml
<?xml version="1.0"?>
<users
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com signup.xsd">
    <user>
        <firstname>Wan</firstname>
        <lastname>Syafiqah</lastname>
        <username>syafiqah2025</username>
        <password>SyaFiq@123</password>
        <fulladdress>No 8, Jalan Kenangan, Taman Aman</fulladdress>
        <postcode>43000</postcode>
		<city> Shah Alam </city>
        <state>Selangor</state>
        <phone>012-3456789</phone>
        <email>syafiqah@gmail.com</email>
    </user>
	
	 <user>
        <firstname>Asmaa</firstname>
        <lastname>Sofiya</lastname>
        <username>sofiyaa22</username>
        <password>Sofiyaa23?</password>
        <fulladdress>No 12, Jalan Raja Laut, Taman Botani</fulladdress>
        <postcode>05678</postcode>
		<city>Temerloh</city>
        <state>Pahang</state>
        <phone>017-6899012</phone>
        <email>asmaa1@gmail.com</email>
    </user>
	
	 <user>
        <firstname>Afifah</firstname>
        <lastname>Hannani</lastname>
        <username>afifah34</username>
        <password>12Afif@H</password>
        <fulladdress>No 10, Jalan Aman , Taman Cempaka</fulladdress>
        <postcode>43890</postcode>
        <city>Ampang</city>
		<state>Wilayah Persekutuan Kuala Lumpur</state>
        <phone>017-0914567</phone>
        <email>afifah@gmail.com</email>
    </user>
	
	 <user>
        <firstname>Nurul</firstname>
        <lastname>Hasanah</lastname>
        <username>Hasanah09</username>
        <password>hasanaH@@3</password>
        <fulladdress>No 60, Jalan Batu Kawan, Taman Eco</fulladdress>
        <postcode>06622</postcode>
		<city>Butterworth</city>
        <state>Pulau Pinang</state>
        <phone>011-0980125</phone>
        <email>hasanah@gmail.com</email>
    </user>
	
	 <user>
        <firstname>Alisya</firstname>
        <lastname>Law</lastname>
        <username>alisyaaa</username>
        <password>AliSya@2</password>
        <fulladdress>No 01, Jalan Othman, Taman Kayangan</fulladdress>
        <postcode>05609</postcode>
		<city>Miri</city>
        <state>Sarawak</state>
        <phone>011-7770004</phone>
        <email>alisya@gmail.com</email>
    </user>
</users>
